# Generated by Django 2.1 on 2018-08-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180824_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='report_comment',
            field=models.BooleanField(default=False),
        ),
    ]
